# Generated by Django 4.1.1 on 2023-02-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('text_info', models.CharField(max_length=1000, verbose_name='Açıklama')),
                ('text', models.TextField(max_length=5000, verbose_name='Text')),
                ('yazar', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf')),
            ],
        ),
    ]
