# Generated by Django 4.1.1 on 2023-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeni',
            name='fiyat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fiyatı'),
        ),
        migrations.AddField(
            model_name='yeni',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ev Shibi'),
        ),
    ]
