# Generated by Django 4.1.1 on 2023-02-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_yeni_fiyat_yeni_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeni',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf'),
        ),
    ]
