# Generated by Django 4.1.1 on 2023-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_yeni_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeni',
            name='image_5',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf'),
        ),
    ]
