# Generated by Django 4.1.1 on 2023-03-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_yeni_image_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeni',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih'),
        ),
    ]
