# Generated by Django 4.1.1 on 2023-03-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_yazar_yeni_danışman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeni',
            old_name='danışman',
            new_name='advisor',
        ),
    ]
