# Generated by Django 4.1.1 on 2023-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_yeni_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeni',
            name='feature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Özellik'),
        ),
    ]
