# Generated by Django 4.1.1 on 2023-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_yeni_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeni',
            name='feature',
            field=models.CharField(max_length=100, verbose_name='Özellik'),
        ),
        migrations.AlterField(
            model_name='yeni',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 1'),
        ),
        migrations.AlterField(
            model_name='yeni',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 2'),
        ),
        migrations.AlterField(
            model_name='yeni',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 3'),
        ),
        migrations.AlterField(
            model_name='yeni',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 4'),
        ),
        migrations.AlterField(
            model_name='yeni',
            name='image_5',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 5'),
        ),
        migrations.AlterField(
            model_name='yeni',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ev Sahibi'),
        ),
    ]
