# Generated by Django 4.1.1 on 2023-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_yeni_feature_alter_yeni_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeni',
            name='bd_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Bd Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='yeni',
            name='text_info',
            field=models.TextField(max_length=1000, verbose_name='Açıklama'),
        ),
    ]
